# Generated by Django 5.0.1 on 2024-01-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
